//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWBA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NWBAEntities : DbContext
    {
        public NWBAEntities()
            : base("name=NWBAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<account> accounts { get; set; }
        public DbSet<accountTypeLookup> accountTypeLookups { get; set; }
        public DbSet<addressTypeLookup> addressTypeLookups { get; set; }
        public DbSet<billPay> billPays { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<customerAddress> customerAddresses { get; set; }
        public DbSet<customerPhoneNumber> customerPhoneNumbers { get; set; }
        public DbSet<login> logins { get; set; }
        public DbSet<Payee> Payees { get; set; }
        public DbSet<periodLookup> periodLookups { get; set; }
        public DbSet<phoneTypeLookup> phoneTypeLookups { get; set; }
        public DbSet<StateLookup> StateLookups { get; set; }
        public DbSet<transactionTypeLookup> transactionTypeLookups { get; set; }
    }
}
